---
version: "3.6"
services:
  smokeping:
    image: linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/vincent/docker/smokeping/config:/config
      - /home/vincent/docker/smokeping/data:/data
    ports:
      - 8095:80
    restart: unless-stopped
